### ISSUE TITLE
Create a REST endpoint to return the status of the server

### ISSUE THREAD

**Issue by RichardInnocent** [adlkucewicz/ChatIO#4]
We need to figure out how to create a REST endpoint in Django. This is what we'll be creating for every new route we add in.

A good start might be to create a route as follows:

Route: `/status`
Request type: GET

Response content type: application/json
Expected response:
```json
{
  "status": "Running"
}
```

**Comment by RichardInnocent** [comment]
Addressed in [this PR](https://github.com/adlkucewicz/ChatIO/pull/9).

**Comment by adlkucewicz** [comment]
Just run the site, thanks for adding that in. I need to do more research about end points. I'm starting to realise there is a disconnect between my knowledge and the appropriate terminology haha.

**Comment by RichardInnocent** [comment]
Haha I basically just mean a specific path in the system. Described [here](https://searchapparchitecture.techtarget.com/definition/API-endpoint#:~:text=An%20API%20endpoint%20is%20a,server%20and%20receiving%20a%20response.).

**Comment by RichardInnocent** [comment]
Path added.
